language: php

php:
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - "mkdir -p ~/.composer"
  - openssl aes-256-cbc -K $encrypted_c3a9b393b141_key -iv $encrypted_c3a9b393b141_iv -in .travis.composer.config.json.enc -out ~/.composer/config.json -d
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - travis_retry vendor/bin/coveralls
