language: php

php:
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json
  - composer self-update
  - composer install
  - composer require satooshi/php-coveralls:dev-master

script:
  - vendor/bin/phpunit --coverage-text

after_script:
  - vendor/bin/coveralls
